Refactor

diff --git a/inst b/inst
--- a/inst
+++ b/inst
@@ -1,4 +1,7 @@
 #!/bin/sh
 
-if grep -qF -e '\`' -e '\"' "${1:?}"; then echo 'ERROR' >&2; exit 1; fi
+if grep -qF -e '\"' -e '\`' "${1:?}"; then
+    printf '%s\n' "ERROR: template contains \\\" or \\\`: $1" >&2;
+    exit 1;
+fi
 eval "printf '%s\\n' \"$(sed 's/"/\\"/g;s/`/\\`/g' "$1")\""
